@startuml

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами
class "Практика" as MyClass {
  ' Атрибуты (поля класса)
  - attribute1: ФИО студента
  - attribute2: Инструкция
  - attribute3: Шаблон документов
  - attribute4: Скан документов
  - attribute5: Список предприятий
  - attribute6: Список руководителей
  - attribute7: Список тем
  ' Методы (функции класса)
  + method1(param: string): Просмотр и скачивание инструкции
  + method2(): Переход на страницу с информацией
  + method3(param1: int, param2: bool): выбор предприятия, руководителя, темы
  + method4(): Открыть шаблон документов
  + method5(): Добавить скан документов
}

' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"
MyClass--BRS

' Настройка стиля для прямоугольника
skinparam class {
    BackgroundColor #FFF
    BorderColor #000
    ArrowColor #000
    FontName Arial
}

' Класс с атрибутами и методами
class "БРС" as BRS {
  ' Атрибуты (поля класса)
  - attribute1: Название дисциплины
  - attribute2: ФИО преподавателя
  - attribute3: Итоги по дисциплине
  - attribute4: Общий балл за лекции
  - attribute5: Общий балл за практики
  - attribute6: Текущая аттестация по лекции
  - attribute7: Текущая аттестация по практике
  - attribute8: Промежуточная аттестация по лекции
  - attribute9^ Промежуточная аттестация по практике
  - 
  ' Методы (функции класса)
  + (): void
  +  (): int
  + method3(param1: int, param2: bool): string
}
' Можно добавить связь с другим классом (опционально)
' class AnotherClass
' MyClass --> AnotherClass : "использует"

@enduml